[package]
name = "quanta"
version = "0.1.0"
authors = ["Paweł Grabarz <frizi09@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
frunk = "0.3.1"

[dev-dependencies]
approx = "0.3.2"
