export const SET_ACTIVE_LEVEL = 'SET_ACTIVE_LEVEL';
export const UPDATE_GRID_CELL = 'UPDATE_GRID_CELL';

export const SET_ACTIVE_CELL = 'SET_ACTIVE_CELL';
export const RESET_ACTIVE_CELL = 'RESET_ACTIVE_CELL';
export const SET_ACTIVE_CELL_COORDINATES = 'SET_ACTIVE_CELL_COORDINATES';

export const CELL_SELECTED = 'CELL_SELECTED';
export const CELL_UNSELECTED = 'CELL_UNSELECTED';
export const SET_MOVE_SOURCE = 'SET_MOVE_SOURCE';
export const RESET_MOVE_SOURCE = 'RESET_MOVE_SOURCE';

export const SET_CURRENT_TOOLS = 'SET_CURRENT_TOOLS';
export const RESET_CURRENT_TOOLS = 'RESET_CURRENT_TOOLS';
export const ADD_TO_CURRENT_TOOLS = 'ADD_TO_CURRENT_TOOLS';
export const REMOVE_FROM_CURRENT_TOOLS = 'REMOVE_FROM_CURRENT_TOOLS';
