export const SET_GAME_STATE = 'SET_GAME_STATE'
export const SET_SIMULATION_STATE = 'SET_SIMULATION_STATE'

export const SET_FATE_CELLS = 'SET_FATE_CELLS'
export const RESET_FATE_CELLS = 'RESET_FATE_CELLS'

export const SET_ACTIVE_CELL = 'SET_ACTIVE_CELL'
export const RESET_ACTIVE_CELL = 'RESET_ACTIVE_CELL'

export const SET_CURRENT_LEVEL_ID = 'SET_CURRENT_LEVEL_ID'

export const SET_HOVERED_CELL = 'SET_HOVERED_CELL'
export const SET_HOVERED_PARTICLE = 'SET_HOVERED_PARTICLE'

export const SET_CURRENT_TOOLS = 'SET_CURRENT_TOOLS'
export const RESET_CURRENT_TOOLS = 'RESET_CURRENT_TOOLS'
export const ADD_TO_CURRENT_TOOLS = 'ADD_TO_CURRENT_TOOLS'
export const REMOVE_FROM_CURRENT_TOOLS = 'REMOVE_FROM_CURRENT_TOOLS'

// OPTIONS STATE MUTATIONS NAMES:
export const SET_OPTIONS = 'SET_OPTIONS'
export const RESET_OPTIONS = 'RESET_OPTIONS'
export const SET_GAME_SPEED_INTERVAL = 'SET_GAME_SPEED_INTERVAL'
